version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      microsoft-extensions:
        patterns: ["Microsoft.Extensions.*"]
      ef-core:
        patterns: ["Microsoft.EntityFrameworkCore*"]
      serilog:
        patterns: ["Serilog*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
