// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignRelay.Server.Data;

#nullable disable

namespace SignRelay.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607194202_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SignRelay.Server.Data.JobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseAgentId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaseAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LeaseExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LeasedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasMaxLength(64000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalUnsignedBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("JobTokenHash")
                        .IsUnique();

                    b.HasIndex("LeaseTokenHash");

                    b.HasIndex("Status", "ExpiresUtc");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
