<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>dotnet-SignRelay.Agent-23564bc6-3cd8-49c2-b61e-5a6d5d86af32</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SignRelay.Contracts\SignRelay.Contracts.csproj" />
  </ItemGroup>
</Project>
