<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SignRelay.Cli</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <PackageId>Nefarius.Tools.SignRelay</PackageId>
    <ToolCommandName>signrelay</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SignRelay.Contracts\SignRelay.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

</Project>
